---
apiVersion: gcp.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
machineImages:
- name: coreos
  version: 2135.6.0
  image: projects/coreos-cloud/global/images/coreos-stable-2135-6-0-v20190801
etcd:
  storage:
    className: gardener.cloud-fast
    capacity: 25Gi
#  backup:
#    schedule: "0 */24 * * *"
#healthCheckConfig:
#  syncPeriod: 30s