load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["requeue_error.go"],
    importpath = "github.com/gardener/gardener-extensions/pkg/controller/error",
    visibility = ["//visibility:public"],
)
