load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["cloudinit.go"],
    importpath = "github.com/gardener/gardener-extensions/controllers/os-coreos-alibaba/pkg/coreos-alibaba/internal/cloudinit",
    visibility = ["//controllers/os-coreos-alibaba/pkg/coreos-alibaba:__subpackages__"],
)
