---
apiVersion: aws.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
machineImages:
- name: coreos
  version: 2135.6.0
  regions:
  - name: eu-central-1
    ami: ami-034fd8c3f4026eb39
  - name: eu-west-1
    ami: ami-0b4e04c2cc22a915e
  - name: us-east-1
    ami: ami-04e51eabc8abea762
  - name: us-east-2
    ami: ami-00893b3a357694f05
  - name: ap-southeast-1
    ami: ami-03b2848db9a1e8331
  - name: ap-southeast-2
    ami: ami-0f2a464ec2d360ab3
etcd:
  storage:
    className: gardener.cloud-fast
    capacity: 80Gi
#  backup:
#    schedule: "0 */24 * * *"
#healthCheckConfig:
#  syncPeriod: 30s