#!/bin/bash
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function usage {
    cat <<EOM
Usage:
generate-controllerregistration <name> <kind> <type> <chart-dir> <dest>

    <name>          Name of the controller registration to generate.
    <kind>          Kind of the controller registration.
    <type>          Type of the controller registration.
    <chart-dir>     Location of the chart directory.
EOM
    exit 0
}

NAME="$1"
KIND="$2"
TYPE="$3"
CHART_DIR="$4"
DEST="$5"

( [ -z "$NAME" ] || [ -z "$KIND" ] || [ -z "$TYPE" ] || [ -z "$CHART_DIR" ] || [ -z "$DEST" ] ) && usage || :

temp_dir="$(mktemp -d)"
helm package "$CHART_DIR" --destination "$temp_dir"
chart="$(cat $temp_dir/*.tgz | base64 | tr -d '\n')"
rm -r "$temp_dir"

mkdir -p "$(dirname "$DEST")"

cat <<EOM > "$DEST"
---
apiVersion: core.gardener.cloud/v1alpha1
kind: ControllerRegistration
metadata:
  name: $NAME
spec:
  resources:
  - kind: $KIND
    type: $TYPE
  deployment:
    type: helm
    providerConfig:
      chart: $chart
EOM

echo "Successfully generated controller registration at $DEST"
